### ISSUE TITLE
HA Companion iOS app login error

### ISSUE THREAD

**Issue by astraelise** [openlumi/homeassistant_on_openwrt#11]
After getting the HA instance running, logging in from safari or a desktop works, but trying to use the iOS app after logging in leads to the following error:

`Error Code: alamofire.AFError error 9`

The only resource I could find related to this was [this](https://community.home-assistant.io/t/ha-companion-app-alamofire-aferror-9/355504/12)

However, turning off private address didn't work.

I have no idea if this could be due to HA or having HA on openwrt, if I am being a bother in anyway I more than happy to close this issue.

**Comment by devbis** [comment]
Hi, thank you for the report. Unfortunately, I don't have iOS devices to check the issue mentioned. Let's keep this ticket open for a while, maybe one has a solution for the issue.

BTW, you can use a custom component https://github.com/AlexxIT/Dataplicity as a workaround for the issue, it creates an HTTPS connection to your instance for free and you could use HA web UI as well.

**Comment by astraelise** [comment]
> BTW, you can use a custom component https://github.com/AlexxIT/Dataplicity as a workaround for the issue, it creates an HTTPS connection to your instance for free and you could use HA web UI as well.

I just got to try this workaround and unfortunately it leads to the same error. I do appreciate the help though. ~I'll try adding `mobile_app:` to configuration.yaml~ (That doesn't seem to be the issue either, since I have `default_config:` in the file).

**Comment by devbis** [comment]
`default_config:` doesn't include mobile_app by default on this configuration. It is excluded during installation to reduce memory consumption.

**Comment by astraelise** [comment]
> `default_config:` doesn't include mobile_app by default on this configuration
 
Should I include it? I've done some digging and I uncommented `mobile_app` in the config flow, however when opening the integration, it causes the HA instance to crash.

**Comment by devbis** [comment]
You should enable it in the config, and probably, in the generated flows. I don't use the app, so I can't give you the exact steps.
