### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by dsultanr** [openlumi/homeassistant_on_openwrt#15]
Trying to install on a fresh OpenWrt and getting an error: No space left on device. But there is more than 6 Gb free space. Any thoughts?

[here is the full log](https://pastebin.com/h5PXN0e2)

![image](https://user-images.githubusercontent.com/1683476/167418825-fb13e080-fa17-4ec3-a426-a0905275ed3c.png)

**Comment by devbis** [comment]
Hi! pip downloads files to the `/tmp` dir on install and it is mapped to RAM. 
You have 64MB available which could be not enough for installing and running Home Assistant.
If you are sure you can try this suggestion http://naoko.github.io/pip-install-no-space-left/

```sh
export TMPDIR=/root
wget ...
```

**Comment by dsultanr** [comment]
Thanks for a quick reply!

My board is KN-1710. I believe it has 128 MB RAM. But I have flashed a
firmware for Keenetic Extra II because only that model is available in
OpenWrt. Could this be the case of 64 megabytes only RAM available?

пн, 9 мая 2022 г., 23:24 Ivan Belokobylskiy ***@***.***>:

**Comment by devbis** [comment]
I think /tmp uses 50% of RAM, but as the limit. So it could work with your setup. But I'm not sure, the latest versions require more memory for installation.

**Comment by dsultanr** [comment]
I have already installed HA and planning to use this install as a central
unit to control home automatics. Mostly for Temperature sensors and
relays.  Is the HA on a such boards reliable? Do you have any long term
experience?

**Comment by devbis** [comment]
It has some restrictions, usually memory limits and you have to control memory consumption, like enabling history only for specific devices. But basically, it works as a 'big' standalone installation.

**Comment by dsultanr** [comment]
Thanks. Do you have ocassionaly an experience with a Node-Arduino-Firmata on OpenWRT? It could be a less consuming alternative to HA

**Comment by lmahmutov** [comment]
for install on small ram device first increase tmpfs 
mount -t tmpfs -o remount,size=1G tmpfs /tmp

**Comment by AapoTahkola** [comment]
I had to use this because there were some odd looking errors in home-assistant.log . I have already destroyed all evidence so someone else with a fresh install is going to have to try.
If there is need for future options during install just cut 'n' paste. I crafted the scripting style with that in mind. Busybox shell switch syntax burns my eyes.
```
#from https://stackoverflow.com/questions/40395894/calculate-percentage-of-free-memory-using-bash-scripts-in-linux

memtotal=`cat /proc/meminfo | grep MemTotal | awk '{print $2}'`;
min_mem=$(( 256 * 1024 ));
ram_resize_cmd="mount -t tmpfs -o remount,size=1G tmpfs /tmp";

if [ $memtotal -lt $min_mem ]; then
        echo "Looks like you have less or equivalent to $min_mem kb of RAM memory."
        echo "Installation will most likely fail unless /tmp is resized."
        echo "Select y to resize /tmp. This change will be effective until next reboot."
        echo "This will run '$ram_resize_cmd'"
        echo "Select n to continue without resizing."
        echo "Select q to quit."

        read reply
        #echo "$reply"

        if [ $reply == "y" ]; then
                eval "$ram_resize_cmd"
        fi

        if [ $reply == "n" ]; then
                echo "Continuing."
        fi

        if [ $reply == "q" ]; then
                exit 1
        fi

fi
```

**Comment by AapoTahkola** [comment]
I actually think first running HA might cause some more pip commands to propagate needing more /tmp mem so it might still fail.
Having /tmp resized in /etc/rc.local sounds like a bad idea so I think it would be better if HA would start immediately after installation instead of asking to reboot. Asking users to reboot is so lame on linux anyway as there is almost never actual need for it.
