### ISSUE TITLE
Errors when installing

### ISSUE THREAD

**Issue by serpro** [openlumi/homeassistant_on_openwrt#16]
Collected errors:
 * opkg_install_cmd: Cannot install package python3-cryptography.
 * pkg_hash_check_unresolved: cannot find dependency python3-cryptography for python3-pyopenssl
 * pkg_hash_fetch_best_installation_candidate: Packages for python3-pyopenssl found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package python3-pyopenssl.

![image](https://user-images.githubusercontent.com/141711/177512097-40b31f57-42f9-40a6-b211-797ecee48c68.png)

**Comment by devbis** [comment]
The dependency has been missed in OpenWrt builds: https://downloads.openwrt.org/releases/21.02.3/packages/arm_cortex-a9_neon/packages/

Maybe you could try to install ipk from neighbor architecture https://downloads.openwrt.org/releases/21.02.3/packages/arm_cortex-a9/packages/

or wait until packages are rebuilt by OpenWrt core team

**Comment by serpro** [comment]
Thanks @devbis!
I don't know how to install the ipk.. Is this the way of doing it? https://wiki.dd-wrt.com/wiki/index.php/Using_ipkg_to_install_OpenWRT_packages I tried that but I don't have jiffs nor I know how to install it

**Comment by devbis** [comment]
I guess it is better to wait for the OpenWrt team to fix dependencies for pyopenssl or add python3-cryptography back.

**Comment by devbis** [comment]
An update: build log from openwrt https://downloads.openwrt.org/releases/faillogs-22.03/arm_cortex-a9_neon/packages/python-cryptography/compile.txt

Cryptography fails to compile.

**Comment by devbis** [comment]
Here is the merged fix. https://github.com/openwrt/packages/pull/18887
Waiting for the package to be built.

**Comment by serpro** [comment]
Thank you! How do I update to the latest version?

**Comment by devbis** [comment]
The file is compiled and is located in feeds. To update just run the script once again.
