### ISSUE TITLE
Cannot install package python3-numpy on OpenWrt 22.03.0-rc4

### ISSUE THREAD

**Issue by AapoTahkola** [openlumi/homeassistant_on_openwrt#17]
I just removed the package install from the script and everything seems fine so far. Maybe just take out this package from the main list and try-and-let-fail if it does not exist.

I think that the requirements are way off though. Newifi-D1 OpenWrt 22.03.0-rc4 with no much installed and storage is at 456 MB used of 1000MB after install. I would much rather avoid cross compiling but I am not sure openwrt can compile even with big extroot. Swap file is something like 50MB of 256MB used. 
I think it would be better to have something like:
mount | grep overlay | grep "/dev/sd"
to check extroot exists and suggest usb extroot with ssd drive or hd before proceeding with install. I do not think there are any routers with these kinds of available disk space. I could see this this kind of script doing some pretty severe damage to routers not up to the task. Also simple bash-fu "free | grep Swap" would be a good requirement.

Anyway, I shall proceed with the painful task of configuring HA but the user interface already feels much faster than on much higher specified orangepi pc I had it on previously. I know, dusty old dual core MIPS beating modern quad core Arm... I think it might be because people are using slow TF cards with raspberries and orange pi.

**Comment by devbis** [comment]
I see, it depends on hard floating point architecture. https://github.com/openwrt/packages/blob/master/lang/python/numpy/Makefile#L38

And your arch has soft floats. 
I don't remember the exact component that requires numpy, possibly it is for some camera components. 
Anyway, I moved it to the optional requirement.

**Comment by AapoTahkola** [comment]
There are some numpy related errors in /var/log/home-assistant.log . I cannot make much out of the errors and now something weird happened and it went completely empty. I post some of the logs when I get it back working.

transmission broke on 22.03 and no one has not bothered to release a fixed package yet so I might just as well fix it for myself. Not backing out of 22.03!

**Comment by AapoTahkola** [comment]
Seems a bit of a strange decision to just axe it.
