### ISSUE TITLE
Integration error: ffmpeg - Integration 'ffmpeg' not found.

### ISSUE THREAD

**Issue by heplus1s** [openlumi/homeassistant_on_openwrt#18]
Unable to set up dependencies of homekit. Setup failed for dependencies: ffmpeg
I already have FFmpeg installed via opkg, but the ffmpeg path in configuration.yaml shows these prompts whether or not I set it.Homekit and Onvif cannot be installed

**Comment by devbis** [comment]
ffmpeg component is removed during installation to save space. Copy it back If you want to try it out. (See readme)

**Comment by youngstill** [comment]
still can not installed homekit after copy the ffmpeg components back, it just keep on configing

**Comment by devbis** [comment]
Probably you need to install ffmpeg package and fix dependency versions in manifest.json

**Comment by the-brown-fox** [comment]
Installing "ffmpeg" via the openwrt "software" section can help, unfortunately it will still tell you unable to find "orjason.orjson".
aka not working still

**Comment by devbis** [comment]
orjson is a rust-based package and cannot be installed on Openwrt. You have to modify the component to use built-in `json` package.

**Comment by smile901122** [comment]
the same question...can't believe that ha core can not install homekit...

**Comment by devbis** [comment]
ha core can, but patched version for OpenWrt cannot. It changes dependencies and HA source code to run with the libraries that OpenWrt provides. Some of them are outdated, some are missing. Homekit without cameras works (at least on 2022.11), but you should remove all the depencencies from manifest.
