### ISSUE TITLE
Adding components

### ISSUE THREAD

**Issue by MSITETOP** [openlumi/homeassistant_on_openwrt#2]
Hi, how to add components and configs?
How configs miio component?
I deleted the integration weather, how do I get it back?

**Comment by Zoolombo** [comment]
I have the same questions

**Comment by devbis** [comment]
You have to download tar.gz from https://pypi.org/project/homeassistant/2021.1.5/#files
Then extract the content and copy the required components to `/usr/lib/python3.7/site-packages/homeassistant-2021.1.5-py3.7.egg/homeassistant/components`

If the component uses the frontend wizard, you may want to uncomment the corresponding line in `/usr/lib/python3.7/site-packages/homeassistant-2021.1.5-py3.7.egg/homeassistant/generated/config_flows.py` also.

**Comment by devbis** [comment]
I added a note to the main instruction 
https://github.com/openlumi/homeassistant_on_openwrt/commit/4e49c70411564d8e4c4b2d75b828f24c1b377cb6
