### ISSUE TITLE
Pip module securetar required

### ISSUE THREAD

**Issue by zyphlar** [openlumi/homeassistant_on_openwrt#21]
The backup module requires the securetar python module in order to install successfully.

**Comment by devbis** [comment]
It is installed automatically in /etc/homeassistant/deps/ during the first boot.

**Comment by zyphlar** [comment]
For some reason I had to install it manually despite everything else in the install script seemingly working, unsure why

**Comment by devbis** [comment]
Added the dependency to the script.
