### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by vaio386064343** [openlumi/homeassistant_on_openwrt#23]
**Is it possible to have it upgrade to the latest version  automatically?** 
       **I have tried to modify the _$HOMEASSISTANT_MAJOR_VERSION to 2022.12_ in .sh in order to update the Homeassistant to ver 2022.12, but it failed.** 

Error Messages:

	Using /usr/lib/python3.9/site-packages
	Finished processing dependencies for pycognito==2022.1.0
	Installing python-ipp...
	/tmp/python-ipp-0.12.1
	sed: requirements.txt: No such file or directory
	
	Using /usr/lib/python3.9/site-packages
	Finished processing dependencies for pycognito==2022.1.0
	Installing python-ipp...
	/tmp/python-ipp-0.12.1
	python3: can't open file '/tmp/python-ipp-0.12.1/setup.py': [Errno 2] No such file or directory

How to fix it or update?

**Comment by devbis** [comment]
Home assistant is developing fastly and with every new release, one has to adapt this script for new changes. 
You can modify this script to run it with newer versions. It requires researching what is broken and updating the script to keep it able to run HA on OpenWrt.
Your PRs are welcome!

**Comment by devbis** [comment]
The script was updated to install HomeAssistant 2022.12.x
