### ISSUE TITLE
pip complaining about update

### ISSUE THREAD

**Issue by littleboot** [openlumi/homeassistant_on_openwrt#27]
This does not seem to be an issue but a quality of life improvement. The output of the script looks better without these messages.
```
[notice] A new release of pip available: 22.2.2 -> 22.3.1
[notice] To update, run: pip install --upgrade pip
```
Every package that is installed using pip will result in a message about an message that there is an update for pip available.

Fix:
add `pip install --upgrade pip` to the script. before pip install is called.

I had issues before with a package not installing, an update to setuptools fixed this for me. So maybe also add:
`pip install --upgrade setuptools`

**Comment by devbis** [comment]
It always complains, but pip is a preinstalled package so I don't want to overwrite the packaged version.
All missing files from newer features are downloaded with the script.
