### ISSUE TITLE
error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by Spp595** [openlumi/homeassistant_on_openwrt#30]
[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: pip install --upgrade pip
Installing python-miio...
Processing /tmp/python-miio-0.5.12
  error: subprocess-exited-with-error
 
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 2
  ╰─> See above for output.
 
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Installing build dependencies ... error
error: subprocess-exited-with-error
 
× pip subprocess to install build dependencies did not run successfully.
│ exit code: 2
╰─> See above for output.
 
note: This error originates from a subprocess, and is likely not a problem with pip.
 
[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: pip install --upgrade pip
root@OpenWrt:/# pip3 uninstall homeassistant
WARNING: Skipping homeassistant as it is not installed.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

FULL LOGS: https://pastebin.com/ybGLhFEZ

**Comment by devbis** [comment]
What hardware do you use? Reboot and try again, it could be memory issues.

**Comment by Spp595** [comment]
> Какое оборудование вы используете? Перезагрузитесь и повторите попытку, возможно, проблемы с памятью.

keenetic omni II. Изначально у меня была ошибка нехватки памяти для pip и я изменил стандартную папку tmp в другом месте. Я пытался уже установить несколько раз ( с перезапуском) ничего не помогает.

**Comment by devbis** [comment]
64 Mb ram is not enough for installing home assistant. 
Minimum requirements are 256 Mb RAM + 256 Mb of disk storage

**Comment by Spp595** [comment]
> 64 Мб оперативной памяти недостаточно для установки домашнего помощника. Минимальные требования: 256 Мб оперативной памяти + 256 Мб дискового пространства.

Ну я перенес корень openwrt на флешку, добавил swap и поменял расположение tmp. Теперь всего хватает

**Comment by devbis** [comment]
Logs don't contain any useful information. I suppose it is a RAM issue. You may think of your hardware as of not suitable for this installation.

**Comment by Spp595** [comment]
> Журналы не содержат никакой полезной информации. Я предполагаю, что это проблема оперативной памяти. Вы можете подумать, что ваше оборудование не подходит для этой установки.

Ок(

**Comment by Spp595** [comment]
(
