### ISSUE TITLE
Installation on External Storage

### ISSUE THREAD

**Issue by loyukfai** [openlumi/homeassistant_on_openwrt#33]
Is there a way to install on external storage (e.g. USB)?

Most router's built-in storage is not big enough.

Cheers.

**Comment by devbis** [comment]
I haven't tried this approach but you may move all your overlay to external storage. https://openwrt.org/docs/guide-user/additional-software/extroot_configuration

But if you ext storage is big enough, you could try to install HA in docker to ext storage if your architecture supports it.

**Comment by loyukfai** [comment]
extroot seems overkill for me 😅

I just want to install HA and relevant stuffs to external storage. Right now, all the Python stuffs are already too big for internal storage...

Cheers

**Comment by loyukfai** [comment]
Sorry someone on OpenWrt forum just reminded me that most routers probably wouldn't have enough memory to run HA.

Forget it.

**Comment by AG12r** [comment]
Yes, it works with this instruction (https://openwrt.org/docs/guide-user/additional-software/extroot_configuration)
