### ISSUE TITLE
Is it HomeAssistant OS or docker container?

### ISSUE THREAD

**Issue by kartman521** [openlumi/homeassistant_on_openwrt#34]
Hello! 
Does this module install HomeAssistant OS and allow you to install addons such as MQTT? (Or its just a docker container)
I use x86 openwrt as host system, will Zigbee USB sticks detect and work with this instance?

**Comment by devbis** [comment]
No, it is just a script that installs Home assistant as a system-wide python package. 
It uses prebuilt Openwrt python packages and remove components to run a minimum configuration.
If you need docker image you may use original HA images/containers from the main project.
