### ISSUE TITLE
bluetooth to wifi proxy support missing?

### ISSUE THREAD

**Issue by saket424** [openlumi/homeassistant_on_openwrt#39]
Has anyone managed to get btproxy to wifi working ? I flashed a esp32 with btproxy enabled but i am unable to autodiscover a new govee-ble temperature and humidity sensor on this stripped down home assistant. The same setup works fine on a full install of home assistant on a raspberry pi

Any ideas on what settings to enable for this

**Comment by devbis** [comment]
You may copy bluetooth and esphome components from the original home assistant archive and fix possible errors. I excluded bluetooth support as it required precompiled library binaries for the arch, which were missing for some architectures. 

https://pypi.org/project/homeassistant/
