### ISSUE TITLE
doesnt appear to work for Banana PI BPI-R4 / missing dependency libbz2

### ISSUE THREAD

**Issue by outbackdingo** [openlumi/homeassistant_on_openwrt#40]
Banana PI BPI-R4

Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency libbz2-1.0 for python3-light
 * pkg_hash_fetch_best_installation_candidate: Packages for python3-light found, but incompatible with the architectures configured
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for python3-pynacl:
 * 	libbz2-1.0
 * opkg_install_cmd: Cannot install package python3-pynacl.

**Comment by devbis** [comment]
What is the sources.list content? Both libraries are in openwrt repo and are present in the main feed.
Maybe your package source is broken as it seems that the board is not supported by official openwrt.

E.g. here https://downloads.openwrt.org/releases/23.05.2/packages/aarch64_cortex-a53/base/  (i don't know the arch for your device)

**Comment by outbackdingo** [comment]
its a trunk build for a Banana PI R4, new board someone has ported to work on openwrt from this repo

```[remote "origin"]
	url = https://github.com/dangowrt/openwrt
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "bpi-r4"]
```

would be a mediatek filogic 
```
CONFIG_HAS_SUBTARGETS=y
CONFIG_HAS_DEVICES=y
CONFIG_TARGET_BOARD="mediatek"
CONFIG_TARGET_SUBTARGET="filogic"
CONFIG_TARGET_PROFILE="DEVICE_bananapi_bpi-r4"
CONFIG_TARGET_ARCH_PACKAGES="aarch64_cortex-a53"
CONFIG_DEFAULT_TARGET_OPTIMIZATION="-Os -pipe -mcpu=cortex-a53"
CONFIG_CPU_TYPE="cortex-a53"
```

**Comment by devbis** [comment]
I mean, /etc/opkg/distfeeds.conf it should point to official openwrt repos

**Comment by outbackdingo** [comment]
yes it does
```
root@d63d77a2b531:~# cat /etc/opkg/distfeeds.conf 
src/gz openwrt_core https://downloads.openwrt.org/snapshots/targets/mediatek/filogic/packages
src/gz openwrt_base https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/base
src/gz openwrt_luci https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/luci
src/gz openwrt_packages https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/packages
src/gz openwrt_routing https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/routing
src/gz openwrt_telephony https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/telephony
root@d63d77a2b531:~# 
```

**Comment by devbis** [comment]
It looks like the file is still there

https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/base/libbz2-1.0_1.0.8-1_aarch64_cortex-a53.ipk

You may try to install it manually via luci.

or in console

```sh
opkg update && opkg install libbz2-1.0
```
