### ISSUE TITLE
Homeassistant have to be restarted before each access.

### ISSUE THREAD

**Issue by Shamanni** [openlumi/homeassistant_on_openwrt#43]
Homeassistant face me "loading data" forever and ever, and ever. Somettimes it reacheable after i restarted it, but only 1 time.

ramips/mt7621

OpenWrt 23.05.0 r23497-6637af95aa / LuCI openwrt-23.05 branch git-24.040.70644-45b9e79

256 RAM

32 GB Extroot

2GB SWAP

**Comment by devbis** [comment]
Can you please add logs from /var/log

**Comment by Shamanni** [comment]
> Can you please add logs from /var/log

[home-assistant.log](https://github.com/openlumi/homeassistant_on_openwrt/files/14319832/home-assistant.log)

and this - 10 minutes older

[home-assistant.2024-02-17.log](https://github.com/openlumi/homeassistant_on_openwrt/files/14319834/home-assistant.2024-02-17.log)

**Comment by devbis** [comment]
Looks like numpy wasn't installed from opkg. And stream component requires it for some reason

**Comment by Shamanni** [comment]
Can it be fixed? I've no mind how to install numpy and for what it needed

**Comment by devbis** [comment]
Numpy is not available for your architecture. I tried to make numpy optional. Please, re-run the script.
