### ISSUE TITLE
it can run on arm aarch64 platform?

### ISSUE THREAD

**Issue by zjyg1993** [openlumi/homeassistant_on_openwrt#45]
As the title wrote,it can run on arm aarch64 platform? what's more, it can extend homtkit ? or only xiaomi smarthome devices ?

**Comment by devbis** [comment]
It can run on Openwrt/aarch64. It installs the original version of HA but patches it to use library versions that are available in OpenWrt repo and keeps only necessary components, others are excluded from the installation to keep it smaller.

Homekit is not included, but you can get it back by copying from an archive and ensure that libraries are installed and versions are correctly mentioned in manifest.json (https://github.com/home-assistant/core/tree/2024.2.5/homeassistant/components/homekit)
Probably, patching is needed.

**Comment by zjyg1993** [comment]
邮件收到，我待会看完，马上就回复你-----------------------------------------------------From Jerome
