### ISSUE TITLE
Whether or not you can specify a mounting location

### ISSUE THREAD

**Issue by PDSB001** [openlumi/homeassistant_on_openwrt#46]
Whether or not you can specify a mounting location？For example, using the specified installation location as an additional command to the installation script

**Comment by don-dolarson** [comment]
Anything new in this topic?

**Comment by devbis** [comment]
All packages are installed to the common opkg location. You may specify a different OpenWrt overlay location and potentially it will work. But it is not tested:

https://openwrt.org/docs/guide-user/additional-software/extroot_configuration
