### ISSUE TITLE
No package python3-gdbm

### ISSUE THREAD

**Issue by Mi-r** [openlumi/homeassistant_on_openwrt#49]
Command _opkg install python3-gdbm_  responds:
_Unknown package 'python3-gdbm'.# openwrt master doesn't have this package_
I read in file ha_install.sh:
_openwrt master doesn't have this package
opkg install python3-gdbm 2>/dev/null || true_
Where can I get the package? Please, help!

**Comment by devbis** [comment]
Python GDBM package is removed from Openwrt 22+. You can safely ignore this message.

**Comment by Mi-r** [comment]
exactly, thank you very much
