### ISSUE TITLE
How i can delete the installed homeassistant?

### ISSUE THREAD

**Issue by paradigmer** [openlumi/homeassistant_on_openwrt#52]
This is different from the version of the home assistant that I used on my raspberry pie, so I'm thinking of installing it through docker. Or can I add something to the current installation?  At a minimum, I can't add a server to the mobile app and add repositories.

**Comment by devbis** [comment]
You can remove all python3-* packages via opkg and delete remaining  /usr/lib/python3.11 folder with all installed libraries. Additionally, /etc/homeassistant may contain configuration and logs
