### ISSUE TITLE
Collected errors:  * opkg_download: Failed to download https://mirrors.cloud.tencent.com/lede/snapshots/targets/armvirt/64/packages/Packages.gz, wget returned 8.

### ISSUE THREAD

**Issue by NoAIGhost** [openlumi/homeassistant_on_openwrt#57]
Collected errors:
 * opkg_download: Failed to download https://mirrors.cloud.tencent.com/lede/snapshots/targets/armvirt/64/packages/Packages.gz, wget returned 8.

**Comment by devbis** [comment]
The link for your feeds is broken. Maybe it is the issue
