### ISSUE TITLE
gdbm install fail

### ISSUE THREAD

**Issue by EricNg8801** [openlumi/homeassistant_on_openwrt#9]
error with running the sh file.
1,sum mismatch  ,I have to install every python3-XXX.ipk with --force-check,
2,no package named python3-gdbm

**Comment by devbis** [comment]
What OpenWrt version do you have? 
What device do you have?
Can you share log output on pastebin.com or so?

`python3-gdbm` is removed from the master branch of OpenWrt, after 21.02 and there is a workaround for it in the script.

**Comment by EricNg8801** [comment]
> What OpenWrt version do you have?
> What device do you have?
> Can you share log output on pastebin.com or so?
> 
> `python3-gdbm` is removed from the master branch of OpenWrt, after 21.02 and there is a workaround for it in the script.

hey there, I  reset my VMware and try to install it , the new error is :

Collected errors:
 * check_data_file_clashes: Package python3-dbm wants to install file /usr/lib/python3.9/lib-dynload/_gdbm.cpython-39.so
        But that file is already provided by package  * python3-gdbm
 * opkg_install_cmd: Cannot install package python3-dbm.

my openwrt info:

Linux version 5.4.140 (runner@fv-az199-487) (gcc version 8.4.0 (OpenWrt GCC 8.4.0 r0-f27a174)) #0 SMP Thu Aug 19 17:36:28 2021
![Screenshot 2021-09-07 171609](https://user-images.githubusercontent.com/90168131/132319070-c99aa3dc-95c4-480b-97d0-8fca9e758678.png)

**Comment by EricNg8801** [comment]
Run opkg --force-overwrite install python3-dbm successfully but new error like this:

WARNING: Discarding https://github.com/zigpy/zigpy-zigate/archive/8772221faa7dfbcd31a3bba6e548c356af9faa0c.zip. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by devbis** [comment]
You may comment out zigbee installation as it is used in openlumi gateway and your setup is different.

**Comment by EricNg8801** [comment]
> You may comment out zigbee installation as it is used in openlumi gateway and your setup is different.

always show me the same tip in every step :-(, I turned into docker and install successfully, thx. anyway
